steps:
  # 1. Build Docker image using the root Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args:
      - 'build'
      - '-t'
      - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '.'
      - '-f'
      - 'Dockerfile'

  # 2. Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args:
      - 'push'
      - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'

  # 3. Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'Deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'update'
      - '$_SERVICE_NAME'
      - '--platform=managed'
      - '--image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region=$_DEPLOY_REGION'
      - '--quiet'

images:
  - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'

substitutions:
  _AR_HOSTNAME: 'europe-west1-docker.pkg.dev'
  _AR_PROJECT_ID: 'coletor-v2-503313'
  _AR_REPOSITORY: 'cloud-run-source-deploy'
  _SERVICE_NAME: 'coletorb2br'
  _DEPLOY_REGION: 'europe-west1'

options:
  logging: CLOUD_LOGGING_ONLY
